// <auto-generated />
using System;
using System.Collections.Generic;
using InspectFlow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InspectFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InspectFlow.Modules.AI.Domain.AiAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<Guid?>("ComparisonId")
                        .HasColumnType("uuid")
                        .HasColumnName("comparison_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("confidence");

                    b.Property<Guid?>("DefectId")
                        .HasColumnType("uuid")
                        .HasColumnName("defect_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error");

                    b.Property<Guid>("InspectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("inspection_id");

                    b.Property<Guid>("InspectionRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("inspection_room_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.PrimitiveCollection<List<Guid>>("MediaIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("media_ids");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_ai_analyses");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_ai_analyses_status");

                    b.HasIndex("InspectionRoomId", "Kind", "Status")
                        .HasDatabaseName("ix_ai_analyses_inspection_room_id_kind_status");

                    b.ToTable("ai_analyses", "ai");
                });

            modelBuilder.Entity("InspectFlow.Modules.Audit.Domain.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_audit_logs_timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_type_entity_id");

                    b.ToTable("audit_logs", "audit");
                });

            modelBuilder.Entity("InspectFlow.Modules.Billing.Domain.BillingEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_event_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.HasKey("Id")
                        .HasName("pk_billing_events");

                    b.HasIndex("Provider", "ProviderEventId")
                        .IsUnique()
                        .HasDatabaseName("ix_billing_events_provider_provider_event_id");

                    b.ToTable("billing_events", "billing");
                });

            modelBuilder.Entity("InspectFlow.Modules.Billing.Domain.CheckoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CheckoutUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("checkout_url");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("plan_code");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderSessionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_checkout_sessions");

                    b.HasIndex("SubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("ux_checkout_sessions_subscription_open")
                        .HasFilter("status = 'Open'");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_checkout_sessions_user_id");

                    b.HasIndex("Provider", "ProviderSessionId")
                        .IsUnique()
                        .HasDatabaseName("ix_checkout_sessions_provider_provider_session_id");

                    b.ToTable("checkout_sessions", "billing");
                });

            modelBuilder.Entity("InspectFlow.Modules.Billing.Domain.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_end");

                    b.Property<DateTimeOffset?>("CurrentPeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_start");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTimeOffset?>("PastDueSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("past_due_since");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("plan_code");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderCustomerId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_customer_id");

                    b.Property<string>("ProviderSubscriptionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_subscription_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_subscriptions_user_open")
                        .HasFilter("status IN ('Pending', 'Active', 'PastDue')");

                    b.HasIndex("Provider", "ProviderSubscriptionId")
                        .HasDatabaseName("ix_subscriptions_provider_provider_subscription_id");

                    b.ToTable("subscriptions", "billing");
                });

            modelBuilder.Entity("InspectFlow.Modules.Companies.Domain.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("contact_email");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.ToTable("companies", "companies");
                });

            modelBuilder.Entity("InspectFlow.Modules.Companies.Domain.CompanyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_company_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_company_members_user_id");

                    b.HasIndex("CompanyId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_company_members_company_id_user_id");

                    b.ToTable("company_members", "companies");
                });

            modelBuilder.Entity("InspectFlow.Modules.Identity.Domain.AgentProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("ServiceArea")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("service_area");

                    b.HasKey("UserId")
                        .HasName("pk_agent_profiles");

                    b.ToTable("agent_profiles", "identity");
                });

            modelBuilder.Entity("InspectFlow.Modules.Identity.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_family_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", "identity");
                });

            modelBuilder.Entity("InspectFlow.Modules.Identity.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", "identity");
                });

            modelBuilder.Entity("InspectFlow.Modules.Identity.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("InspectFlow.Modules.Identity.Domain.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", "identity");
                });

            modelBuilder.Entity("InspectFlow.Modules.Inspections.Domain.Inspection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptBy")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accept_by");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<Guid?>("ComparisonInspectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("comparison_inspection_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid?>("CompletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("completed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<string>("InspectionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("inspection_type");

                    b.Property<string>("Instructions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("instructions");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<DateTimeOffset?>("ReviewStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("review_started_at");

                    b.Property<DateOnly?>("ScheduledDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_date");

                    b.Property<DateTimeOffset?>("SentToTenantAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_to_tenant_at");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TenancyId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenancy_id");

                    b.Property<DateTimeOffset?>("TenantRespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tenant_responded_at");

                    b.Property<Guid?>("TenantRespondedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_responded_by");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_inspections");

                    b.HasIndex("ComparisonInspectionId")
                        .HasDatabaseName("ix_inspections_comparison_inspection_id");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_inspections_property_id");

                    b.HasIndex("TenancyId")
                        .HasDatabaseName("ix_inspections_tenancy_id");

                    b.HasIndex("AgentId", "Status")
                        .HasDatabaseName("ix_inspections_agent_id_status");

                    b.HasIndex("CompanyId", "Status")
                        .HasDatabaseName("ix_inspections_company_id_status");

                    b.HasIndex("Status", "Visibility")
                        .HasDatabaseName("ix_inspections_status_visibility");

                    b.ToTable("inspections", "inspections");
                });

            modelBuilder.Entity("InspectFlow.Modules.Inspections.Domain.InspectionComparison", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AIAnalysis")
                        .HasColumnType("text")
                        .HasColumnName("ai_analysis");

                    b.Property<string>("AgentDecision")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("agent_decision");

                    b.Property<string>("AgentNotes")
                        .HasColumnType("text")
                        .HasColumnName("agent_notes");

                    b.Property<string>("BasicComparison")
                        .HasColumnType("text")
                        .HasColumnName("basic_comparison");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by");

                    b.Property<Guid>("InspectionRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("inspection_room_id");

                    b.Property<Guid?>("LatestAiAnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("latest_ai_analysis_id");

                    b.Property<Guid>("SourceInspectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_inspection_id");

                    b.Property<Guid>("SourceInspectionRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_inspection_room_id");

                    b.Property<Guid>("TargetInspectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_inspection_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_inspection_comparisons");

                    b.HasIndex("InspectionRoomId")
                        .IsUnique()
                        .HasDatabaseName("ix_inspection_comparisons_inspection_room_id");

                    b.HasIndex("SourceInspectionId")
                        .HasDatabaseName("ix_inspection_comparisons_source_inspection_id");

                    b.HasIndex("SourceInspectionRoomId")
                        .HasDatabaseName("ix_inspection_comparisons_source_inspection_room_id");

                    b.HasIndex("TargetInspectionId")
                        .HasDatabaseName("ix_inspection_comparisons_target_inspection_id");

                    b.ToTable("inspection_comparisons", "inspections");
                });

            modelBuilder.Entity("InspectFlow.Modules.Inspections.Domain.InspectionDefect", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AIConfidence")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("ai_confidence");

                    b.Property<string>("AIDescription")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("ai_description");

                    b.Property<bool>("AgentConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("agent_confirmed");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("classification");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("FinalDescription")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("final_description");

                    b.Property<Guid>("InspectionRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("inspection_room_id");

                    b.Property<Guid?>("LatestAiAnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("latest_ai_analysis_id");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_inspection_defects");

                    b.HasIndex("InspectionRoomId")
                        .HasDatabaseName("ix_inspection_defects_inspection_room_id");

                    b.ToTable("inspection_defects", "inspections");
                });

            modelBuilder.Entity("InspectFlow.Modules.Inspections.Domain.InspectionInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessCodeHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("access_code_hash");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InspectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("inspection_id");

                    b.Property<string>("InvitedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("invited_email");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid?>("UsedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("used_by_user_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_inspection_invitations");

                    b.HasIndex("InspectionId")
                        .HasDatabaseName("ix_inspection_invitations_inspection_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_inspection_invitations_token_hash");

                    b.ToTable("inspection_invitations", "inspections");
                });

            modelBuilder.Entity("InspectFlow.Modules.Inspections.Domain.InspectionRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentNotes")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("agent_notes");

                    b.Property<string>("AiDescription")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("ai_description");

                    b.Property<DateTimeOffset?>("AiDescriptionGeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ai_description_generated_at");

                    b.Property<Guid?>("ComparisonInspectionRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("comparison_inspection_room_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<bool>("DefectsFound")
                        .HasColumnType("boolean")
                        .HasColumnName("defects_found");

                    b.Property<string>("FinalDescription")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("final_description");

                    b.Property<DateTimeOffset?>("FinalDescriptionEditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("final_description_edited_at");

                    b.Property<Guid?>("FinalDescriptionEditedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("final_description_edited_by");

                    b.Property<string>("FinalDescriptionSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("final_description_source");

                    b.Property<Guid>("InspectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("inspection_id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<Guid?>("LatestAiAnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("latest_ai_analysis_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OriginalPropertyRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_property_room_id");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("room_type");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_inspection_rooms");

                    b.HasIndex("InspectionId")
                        .HasDatabaseName("ix_inspection_rooms_inspection_id");

                    b.ToTable("inspection_rooms", "inspections");
                });

            modelBuilder.Entity("InspectFlow.Modules.Media.Domain.InspectionRoomMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Caption")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("caption");

                    b.Property<Guid?>("DefectId")
                        .HasColumnType("uuid")
                        .HasColumnName("defect_id");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<Guid>("InspectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("inspection_id");

                    b.Property<Guid>("InspectionRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("inspection_room_id");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("media_type");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("original_filename");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("storage_key");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id")
                        .HasName("pk_inspection_room_media");

                    b.HasIndex("DefectId")
                        .HasDatabaseName("ix_inspection_room_media_defect_id");

                    b.HasIndex("InspectionId")
                        .HasDatabaseName("ix_inspection_room_media_inspection_id");

                    b.HasIndex("InspectionRoomId")
                        .HasDatabaseName("ix_inspection_room_media_inspection_room_id");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ix_inspection_room_media_storage_key");

                    b.ToTable("inspection_room_media", "media");
                });

            modelBuilder.Entity("InspectFlow.Modules.Notifications.Domain.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("Link")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("link");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("RecipientEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("recipient_email");

                    b.Property<Guid?>("RecipientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_user_id");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("subject");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("RecipientUserId", "CreatedAt")
                        .HasDatabaseName("ix_notifications_recipient_user_id_created_at");

                    b.ToTable("notifications", "notifications");
                });

            modelBuilder.Entity("InspectFlow.Modules.Properties.Domain.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postcode");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("property_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_properties");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_properties_company_id");

                    b.ToTable("properties", "properties");
                });

            modelBuilder.Entity("InspectFlow.Modules.Properties.Domain.PropertyRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("room_type");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.HasKey("Id")
                        .HasName("pk_property_rooms");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_property_rooms_property_id");

                    b.ToTable("property_rooms", "properties");
                });

            modelBuilder.Entity("InspectFlow.Modules.Reports.Domain.InspectionReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InspectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("inspection_id");

                    b.Property<int>("LatestVersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("latest_version_number");

                    b.Property<string>("ReportNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("report_number");

                    b.HasKey("Id")
                        .HasName("pk_inspection_reports");

                    b.HasIndex("InspectionId")
                        .IsUnique()
                        .HasDatabaseName("ix_inspection_reports_inspection_id");

                    b.HasIndex("ReportNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_inspection_reports_report_number");

                    b.ToTable("inspection_reports", "reports");
                });

            modelBuilder.Entity("InspectFlow.Modules.Reports.Domain.InspectionReportVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<Guid>("GeneratedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("generated_by");

                    b.Property<string>("PdfSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pdf_sha256");

                    b.Property<long?>("PdfSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("pdf_size_bytes");

                    b.Property<string>("PdfStorageKey")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("pdf_storage_key");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("snapshot_json");

                    b.Property<string>("SnapshotSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("snapshot_sha256");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_inspection_report_versions");

                    b.HasIndex("ReportId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_inspection_report_versions_report_id_version_number");

                    b.ToTable("inspection_report_versions", "reports");
                });

            modelBuilder.Entity("InspectFlow.Modules.Reports.Domain.ReportShareLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_accessed_at");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_report_share_links");

                    b.HasIndex("ReportId")
                        .HasDatabaseName("ix_report_share_links_report_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_report_share_links_token_hash");

                    b.ToTable("report_share_links", "reports");
                });

            modelBuilder.Entity("InspectFlow.Modules.Tenancies.Domain.Tenancy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenancies");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_tenancies_company_id");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_tenancies_property_id");

                    b.ToTable("tenancies", "tenancies");
                });

            modelBuilder.Entity("InspectFlow.Modules.Tenancies.Domain.TenancyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<DateTimeOffset?>("InvitationExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invitation_expires_at");

                    b.Property<string>("InvitationTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("invitation_token_hash");

                    b.Property<DateTimeOffset>("InvitedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invited_at");

                    b.Property<DateTimeOffset?>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<Guid>("TenancyId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenancy_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_tenancy_members");

                    b.HasIndex("InvitationTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_tenancy_members_invitation_token_hash")
                        .HasFilter("invitation_token_hash IS NOT NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tenancy_members_user_id");

                    b.HasIndex("TenancyId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_tenancy_members_tenancy_id_email");

                    b.ToTable("tenancy_members", "tenancies");
                });

            modelBuilder.Entity("InspectFlow.Modules.Tenants.Domain.TenantObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InspectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("inspection_id");

                    b.Property<Guid?>("InspectionRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("inspection_room_id");

                    b.Property<Guid>("ReportVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_version_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_tenant_observations");

                    b.HasIndex("AuthorUserId")
                        .HasDatabaseName("ix_tenant_observations_author_user_id");

                    b.HasIndex("InspectionId")
                        .HasDatabaseName("ix_tenant_observations_inspection_id");

                    b.HasIndex("InspectionRoomId")
                        .HasDatabaseName("ix_tenant_observations_inspection_room_id");

                    b.HasIndex("ReportVersionId")
                        .HasDatabaseName("ix_tenant_observations_report_version_id");

                    b.ToTable("tenant_observations", "tenants");
                });

            modelBuilder.Entity("InspectFlow.Modules.Tenants.Domain.TenantProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.HasKey("UserId")
                        .HasName("pk_tenant_profiles");

                    b.ToTable("tenant_profiles", "tenants");
                });

            modelBuilder.Entity("InspectFlow.Modules.Tenants.Domain.TenantResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("decision");

                    b.Property<Guid>("InspectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("inspection_id");

                    b.Property<Guid>("ReportVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_version_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tenant_responses");

                    b.HasIndex("InspectionId")
                        .HasDatabaseName("ix_tenant_responses_inspection_id");

                    b.HasIndex("ReportVersionId")
                        .HasDatabaseName("ix_tenant_responses_report_version_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tenant_responses_user_id");

                    b.ToTable("tenant_responses", "tenants");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", "identity");
                });

            modelBuilder.Entity("InspectFlow.Modules.AI.Domain.AiAnalysis", b =>
                {
                    b.HasOne("InspectFlow.Modules.Inspections.Domain.InspectionRoom", null)
                        .WithMany()
                        .HasForeignKey("InspectionRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ai_analyses_inspection_rooms_inspection_room_id");
                });

            modelBuilder.Entity("InspectFlow.Modules.Billing.Domain.CheckoutSession", b =>
                {
                    b.HasOne("InspectFlow.Modules.Billing.Domain.Subscription", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_checkout_sessions_subscriptions_subscription_id");
                });

            modelBuilder.Entity("InspectFlow.Modules.Billing.Domain.Subscription", b =>
                {
                    b.HasOne("InspectFlow.Modules.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_users_user_id");
                });

            modelBuilder.Entity("InspectFlow.Modules.Companies.Domain.CompanyMember", b =>
                {
                    b.HasOne("InspectFlow.Modules.Companies.Domain.Company", null)
                        .WithMany("Members")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_members_companies_company_id");

                    b.HasOne("InspectFlow.Modules.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_company_members_users_user_id");
                });

            modelBuilder.Entity("InspectFlow.Modules.Identity.Domain.AgentProfile", b =>
                {
                    b.HasOne("InspectFlow.Modules.Identity.Domain.User", null)
                        .WithOne()
                        .HasForeignKey("InspectFlow.Modules.Identity.Domain.AgentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_profiles_users_user_id");
                });

            modelBuilder.Entity("InspectFlow.Modules.Identity.Domain.RefreshToken", b =>
                {
                    b.HasOne("InspectFlow.Modules.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("InspectFlow.Modules.Identity.Domain.UserRole", b =>
                {
                    b.HasOne("InspectFlow.Modules.Identity.Domain.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("InspectFlow.Modules.Identity.Domain.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InspectFlow.Modules.Inspections.Domain.Inspection", b =>
                {
                    b.HasOne("InspectFlow.Modules.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inspections_users_agent_id");

                    b.HasOne("InspectFlow.Modules.Companies.Domain.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inspections_companies_company_id");

                    b.HasOne("InspectFlow.Modules.Inspections.Domain.Inspection", null)
                        .WithMany()
                        .HasForeignKey("ComparisonInspectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inspections_inspections_comparison_inspection_id");

                    b.HasOne("InspectFlow.Modules.Properties.Domain.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inspections_properties_property_id");

                    b.HasOne("InspectFlow.Modules.Tenancies.Domain.Tenancy", null)
                        .WithMany()
                        .HasForeignKey("TenancyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inspections_tenancies_tenancy_id");
                });

            modelBuilder.Entity("InspectFlow.Modules.Inspections.Domain.InspectionComparison", b =>
                {
                    b.HasOne("InspectFlow.Modules.Inspections.Domain.InspectionRoom", null)
                        .WithMany()
                        .HasForeignKey("InspectionRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inspection_comparisons_inspection_rooms_inspection_room_id");

                    b.HasOne("InspectFlow.Modules.Inspections.Domain.Inspection", null)
                        .WithMany()
                        .HasForeignKey("SourceInspectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inspection_comparisons_inspections_source_inspection_id");

                    b.HasOne("InspectFlow.Modules.Inspections.Domain.InspectionRoom", null)
                        .WithMany()
                        .HasForeignKey("SourceInspectionRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inspection_comparisons_inspection_rooms_source_inspection_r");

                    b.HasOne("InspectFlow.Modules.Inspections.Domain.Inspection", null)
                        .WithMany()
                        .HasForeignKey("TargetInspectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inspection_comparisons_inspections_target_inspection_id");
                });

            modelBuilder.Entity("InspectFlow.Modules.Inspections.Domain.InspectionDefect", b =>
                {
                    b.HasOne("InspectFlow.Modules.Inspections.Domain.InspectionRoom", null)
                        .WithMany("Defects")
                        .HasForeignKey("InspectionRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inspection_defects_inspection_rooms_inspection_room_id");
                });

            modelBuilder.Entity("InspectFlow.Modules.Inspections.Domain.InspectionInvitation", b =>
                {
                    b.HasOne("InspectFlow.Modules.Inspections.Domain.Inspection", null)
                        .WithMany()
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inspection_invitations_inspections_inspection_id");
                });

            modelBuilder.Entity("InspectFlow.Modules.Inspections.Domain.InspectionRoom", b =>
                {
                    b.HasOne("InspectFlow.Modules.Inspections.Domain.Inspection", null)
                        .WithMany("Rooms")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inspection_rooms_inspections_inspection_id");
                });

            modelBuilder.Entity("InspectFlow.Modules.Media.Domain.InspectionRoomMedia", b =>
                {
                    b.HasOne("InspectFlow.Modules.Inspections.Domain.InspectionDefect", null)
                        .WithMany()
                        .HasForeignKey("DefectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inspection_room_media_inspection_defects_defect_id");

                    b.HasOne("InspectFlow.Modules.Inspections.Domain.Inspection", null)
                        .WithMany()
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inspection_room_media_inspections_inspection_id");

                    b.HasOne("InspectFlow.Modules.Inspections.Domain.InspectionRoom", null)
                        .WithMany()
                        .HasForeignKey("InspectionRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inspection_room_media_inspection_rooms_inspection_room_id");
                });

            modelBuilder.Entity("InspectFlow.Modules.Properties.Domain.Property", b =>
                {
                    b.HasOne("InspectFlow.Modules.Companies.Domain.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_properties_companies_company_id");
                });

            modelBuilder.Entity("InspectFlow.Modules.Properties.Domain.PropertyRoom", b =>
                {
                    b.HasOne("InspectFlow.Modules.Properties.Domain.Property", null)
                        .WithMany("Rooms")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_property_rooms_properties_property_id");
                });

            modelBuilder.Entity("InspectFlow.Modules.Reports.Domain.InspectionReport", b =>
                {
                    b.HasOne("InspectFlow.Modules.Inspections.Domain.Inspection", null)
                        .WithMany()
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inspection_reports_inspections_inspection_id");
                });

            modelBuilder.Entity("InspectFlow.Modules.Reports.Domain.InspectionReportVersion", b =>
                {
                    b.HasOne("InspectFlow.Modules.Reports.Domain.InspectionReport", null)
                        .WithMany("Versions")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inspection_report_versions_inspection_reports_report_id");
                });

            modelBuilder.Entity("InspectFlow.Modules.Reports.Domain.ReportShareLink", b =>
                {
                    b.HasOne("InspectFlow.Modules.Reports.Domain.InspectionReport", null)
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_report_share_links_inspection_reports_report_id");
                });

            modelBuilder.Entity("InspectFlow.Modules.Tenancies.Domain.Tenancy", b =>
                {
                    b.HasOne("InspectFlow.Modules.Companies.Domain.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenancies_companies_company_id");

                    b.HasOne("InspectFlow.Modules.Properties.Domain.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenancies_properties_property_id");
                });

            modelBuilder.Entity("InspectFlow.Modules.Tenancies.Domain.TenancyMember", b =>
                {
                    b.HasOne("InspectFlow.Modules.Tenancies.Domain.Tenancy", null)
                        .WithMany("Members")
                        .HasForeignKey("TenancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenancy_members_tenancies_tenancy_id");

                    b.HasOne("InspectFlow.Modules.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tenancy_members_users_user_id");
                });

            modelBuilder.Entity("InspectFlow.Modules.Tenants.Domain.TenantObservation", b =>
                {
                    b.HasOne("InspectFlow.Modules.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_observations_users_author_user_id");

                    b.HasOne("InspectFlow.Modules.Inspections.Domain.Inspection", null)
                        .WithMany()
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_observations_inspections_inspection_id");

                    b.HasOne("InspectFlow.Modules.Inspections.Domain.InspectionRoom", null)
                        .WithMany()
                        .HasForeignKey("InspectionRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tenant_observations_inspection_rooms_inspection_room_id");

                    b.HasOne("InspectFlow.Modules.Reports.Domain.InspectionReportVersion", null)
                        .WithMany()
                        .HasForeignKey("ReportVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_observations_inspection_report_versions_report_versi");
                });

            modelBuilder.Entity("InspectFlow.Modules.Tenants.Domain.TenantProfile", b =>
                {
                    b.HasOne("InspectFlow.Modules.Identity.Domain.User", null)
                        .WithOne()
                        .HasForeignKey("InspectFlow.Modules.Tenants.Domain.TenantProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_profiles_users_user_id");
                });

            modelBuilder.Entity("InspectFlow.Modules.Tenants.Domain.TenantResponse", b =>
                {
                    b.HasOne("InspectFlow.Modules.Inspections.Domain.Inspection", null)
                        .WithMany()
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_responses_inspections_inspection_id");

                    b.HasOne("InspectFlow.Modules.Reports.Domain.InspectionReportVersion", null)
                        .WithMany()
                        .HasForeignKey("ReportVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_responses_inspection_report_versions_report_version_");

                    b.HasOne("InspectFlow.Modules.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_responses_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("InspectFlow.Modules.Identity.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("InspectFlow.Modules.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("InspectFlow.Modules.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("InspectFlow.Modules.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });

            modelBuilder.Entity("InspectFlow.Modules.Companies.Domain.Company", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("InspectFlow.Modules.Identity.Domain.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("InspectFlow.Modules.Identity.Domain.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("InspectFlow.Modules.Inspections.Domain.Inspection", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("InspectFlow.Modules.Inspections.Domain.InspectionRoom", b =>
                {
                    b.Navigation("Defects");
                });

            modelBuilder.Entity("InspectFlow.Modules.Properties.Domain.Property", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("InspectFlow.Modules.Reports.Domain.InspectionReport", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("InspectFlow.Modules.Tenancies.Domain.Tenancy", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
