using InspectFlow.Shared.Localization;

namespace InspectFlow.Infrastructure.Pdf;

/// <summary>The PDF label sets (English and Brazilian Portuguese).</summary>
internal static class ReportPdfTexts
{
    public static readonly ReportPdfText English = new()
    {
        Language = SupportedLanguages.English,
        MonthNames = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
        LongDateFormat = "{0} {1} {2}",
        ShortMonthSuffix = "",
        DocumentTitleFormat = "Inspection report {0}",
        DocumentSubjectFormat = "{0} inspection - {1}",
        InspectionReport = "Inspection Report",
        ReportNumber = "Report no.",
        Version = "Version",
        Generated = "Generated",
        PreparedBy = "Prepared by",
        ImportantInformation = "Important information",
        Disclaimer = "This report records the condition of the property that was visible at the time of the inspection. " +
                     "Descriptions may have been drafted with AI assistance and were reviewed and confirmed by the inspector. " +
                     "Areas not shown or not accessible were not assessed. This report does not determine responsibility or liability for any damage.",
        PropertyType = "Property type",
        InspectionType = "Inspection type",
        InspectionDate = "Inspection date",
        Inspector = "Inspector",
        Tenants = "Tenant(s)",
        Tenancy = "Tenancy",
        TenancyRangeFormat = "{0} to {1}",
        Ongoing = "ongoing",
        ComparedWith = "Compared with",
        ComparedWithFormat = "Move In report {0}",
        RoomsInspected = "Rooms inspected",
        RoomsOverview = "Rooms inspected",
        Room = "Room",
        Photos = "Photos",
        Defects = "Defects",
        Condition = "Condition",
        NoDescription = "No description recorded.",
        NoPhotos = "No photos recorded for this room.",
        NoDefects = "No defects recorded",
        DefectsRecordedFormat = "{0} defect(s) recorded",
        Defect = "Defect",
        Location = "Location",
        InspectorNotes = "Inspector notes",
        PhotoCaptionFormat = "Photo {0}",
        DefectPhotoCaptionFormat = "Defect {0} · photo {1}",
        PhotoUnavailable = "Photo unavailable",
        ComparisonSummaryTitle = "Move In / Move Out comparison summary",
        ComparisonTitle = "Move In vs Move Out",
        Before = "Before · Move In",
        After = "After · Move Out",
        PreviousCondition = "Previous condition",
        CurrentCondition = "Current condition",
        MoveInDefects = "Defects at Move In",
        PossibleChanges = "Possible changes",
        InspectorDecision = "Inspector decision",
        Notes = "Notes",
        InspectionSummary = "Inspection summary",
        DefectsRecorded = "Defects recorded",
        RoomsWithoutDefects = "Rooms without defects",
        RoomsWithDefects = "Rooms with defects",
        DefectsByClassification = "Defects by classification",
        ComparisonOutcome = "Comparison with Move In",
        ReportDetails = "Report details",
        ReportId = "Report ID",
        Company = "Company",
        Page = "Page ",
        PageOf = " of ",
        EnumLabels = new Dictionary<string, string>
        {
            ["MoveIn"] = "Move In", ["MoveOut"] = "Move Out", ["LivingRoom"] = "Living Room", ["DiningRoom"] = "Dining Room",
            ["NewDamage"] = "New damage", ["PreExisting"] = "Pre-existing", ["NormalWear"] = "Normal wear",
            ["UnableToDetermine"] = "Unable to determine", ["Unknown"] = "Not classified",
        },
    };

    public static readonly ReportPdfText PortugueseBrazil = new()
    {
        Language = SupportedLanguages.PortugueseBrazil,
        MonthNames = ["janeiro", "fevereiro", "março", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro", "novembro", "dezembro"],
        LongDateFormat = "{0} de {1} de {2}",
        ShortMonthSuffix = ".",
        DocumentTitleFormat = "Laudo de vistoria {0}",
        DocumentSubjectFormat = "Vistoria de {0} - {1}",
        InspectionReport = "Laudo de Vistoria",
        ReportNumber = "Laudo nº",
        Version = "Versão",
        Generated = "Gerado em",
        PreparedBy = "Emitido por",
        ImportantInformation = "Informações importantes",
        Disclaimer = "Este laudo registra o estado do imóvel que estava visível no momento da vistoria. " +
                     "As descrições podem ter sido redigidas com apoio de IA e foram revisadas e confirmadas pelo vistoriador. " +
                     "Áreas não mostradas ou sem acesso não foram avaliadas. Este laudo não determina responsabilidade por nenhum dano.",
        PropertyType = "Tipo de imóvel",
        InspectionType = "Tipo de vistoria",
        InspectionDate = "Data da vistoria",
        Inspector = "Vistoriador",
        Tenants = "Inquilino(s)",
        Tenancy = "Locação",
        TenancyRangeFormat = "{0} a {1}",
        Ongoing = "em vigor",
        ComparedWith = "Comparado com",
        ComparedWithFormat = "Laudo de entrada {0}",
        RoomsInspected = "Cômodos vistoriados",
        RoomsOverview = "Cômodos vistoriados",
        Room = "Cômodo",
        Photos = "Fotos",
        Defects = "Avarias",
        Condition = "Estado",
        NoDescription = "Nenhuma descrição registrada.",
        NoPhotos = "Nenhuma foto registrada neste cômodo.",
        NoDefects = "Nenhuma avaria registrada",
        DefectsRecordedFormat = "{0} avaria(s) registrada(s)",
        Defect = "Avaria",
        Location = "Local",
        InspectorNotes = "Observações do vistoriador",
        PhotoCaptionFormat = "Foto {0}",
        DefectPhotoCaptionFormat = "Avaria {0} · foto {1}",
        PhotoUnavailable = "Foto indisponível",
        ComparisonSummaryTitle = "Resumo da comparação entre entrada e saída",
        ComparisonTitle = "Entrada x Saída",
        Before = "Antes · Entrada",
        After = "Depois · Saída",
        PreviousCondition = "Estado anterior",
        CurrentCondition = "Estado atual",
        MoveInDefects = "Avarias na entrada",
        PossibleChanges = "Possíveis alterações",
        InspectorDecision = "Decisão do vistoriador",
        Notes = "Observações",
        InspectionSummary = "Resumo da vistoria",
        DefectsRecorded = "Avarias registradas",
        RoomsWithoutDefects = "Cômodos sem avarias",
        RoomsWithDefects = "Cômodos com avarias",
        DefectsByClassification = "Avarias por classificação",
        ComparisonOutcome = "Comparação com a entrada",
        ReportDetails = "Dados do laudo",
        ReportId = "ID do laudo",
        Company = "Empresa",
        Page = "Página ",
        PageOf = " de ",
        EnumLabels = new Dictionary<string, string>
        {
            ["MoveIn"] = "Entrada", ["MoveOut"] = "Saída", ["Periodic"] = "Periódica", ["Other"] = "Outra",
            ["House"] = "Casa", ["Apartment"] = "Apartamento", ["Studio"] = "Studio", ["Townhouse"] = "Sobrado",
            ["Bungalow"] = "Casa térrea", ["Commercial"] = "Comercial",
            ["LivingRoom"] = "Sala de estar", ["Bedroom"] = "Quarto", ["Kitchen"] = "Cozinha", ["Bathroom"] = "Banheiro",
            ["DiningRoom"] = "Sala de jantar", ["Hallway"] = "Corredor", ["Garage"] = "Garagem", ["Garden"] = "Jardim",
            ["Utility"] = "Área de serviço", ["Office"] = "Escritório", ["Balcony"] = "Varanda",
            ["NewDamage"] = "Dano novo", ["PreExisting"] = "Pré-existente", ["NormalWear"] = "Desgaste natural",
            ["Resolved"] = "Resolvido", ["Unchanged"] = "Sem alteração", ["UnableToDetermine"] = "Não foi possível determinar",
            ["Unknown"] = "Não classificada", ["Pending"] = "Pendente",
        },
    };
}
